name: Caching Demo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create File
        run: echo $(date) > DemoFile.txt
        
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: DemoFile.txt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('cache-dependency-file.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Print Content of DemoFile
        run: cat DemoFile.txt
